### ISSUE TITLE
After adding new compnay, page doesn't redirect

### ISSUE THREAD

**Issue by ryanlabouve** [Oladele/noovis_app2_ember2#46]
When you add a new company, it stays on the same page where it should redirect.

Should also show a flash message or something to give user feedback.

![screenshot_5_3_16__9_32_pm](https://cloud.githubusercontent.com/assets/1318878/15005245/ba4b8122-1176-11e6-97ef-4867362db32b.jpg)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/114781003604494/120093137677286)

**Comment by stevenwu** [comment]
That may have been an automatic close through Asana.
